### ISSUE TITLE
Missing library tabulate

### ISSUE THREAD

**Issue by mrchrisadams** [insomniacslk/python-dublin-traceroute#14]
Hi there,

I was trying out you library today, and I had some trouble when running it for the first time - is there a library missing from the requirements.txt/setup.py?

I saw a _missing 'tabulate'  module_ when I ran this command:

```
sudo python -m dublintraceroute trace server.thegreenwebfoundation.org
```

Here's the output:

```
Traceback (most recent call last):
  File "/Users/chrisadams/.pyenv/versions/3.6.10/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/chrisadams/.pyenv/versions/3.6.10/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/chrisadams/.pyenv/versions/3.6.10/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/chrisadams/Library/Caches/pypoetry/virtualenvs/greenflow-LVyxoVJt-py3.6/lib/python3.6/site-packages/dublintraceroute/__init__.py", line 5, in <module>
    from .dublintraceroute import (
  File "/Users/chrisadams/Library/Caches/pypoetry/virtualenvs/greenflow-LVyxoVJt-py3.6/lib/python3.6/site-packages/dublintraceroute/dublintraceroute.py", line 8, in <module>
    from .tracerouteresults import TracerouteResults
  File "/Users/chrisadams/Library/Caches/pypoetry/virtualenvs/greenflow-LVyxoVJt-py3.6/lib/python3.6/site-packages/dublintraceroute/tracerouteresults.py", line 9, in <module>
    import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

I saw the command run to completion after adding the missing library:

```
python -m pip install tabulate
```

Although I was expecting some different output to this (which I'm happy to address separately)

```
Traceroute to server.thegreenwebfoundation.org
  Source port: 12345, destination port: 33434, num paths: 20, min TTL: 1, max TTL: 30, delay: 10, broken NAT: False
  ttl  33434                   33435                   33436                  33437    33438                   33439                   33440                   33441                   33442                   33443                    33444                   33445    33446                   33447    33448    33449                    33450    33451                   33452    33453
-----  ----------------------  ----------------------  ---------------------  -------  ----------------------  ----------------------  ----------------------  ----------------------  ----------------------  -----------------------  ----------------------  -------  ----------------------  -------  -------  -----------------------  -------  ----------------------  -------  -------
    1  fritz.box (8.924 msec)  fritz.box (1.793 msec)  fritz.box (6.77 msec)  *        fritz.box (4.464 msec)  fritz.box (5.624 msec)  fritz.box (4.435 msec)  fritz.box (7.192 msec)  fritz.box (7.988 msec)  fritz.box (13.242 msec)  fritz.box (5.657 msec)  *        fritz.box (5.543 msec)  *        *        fritz.box (11.200 msec)  *        fritz.box (8.273 msec)  *        *
```

For comparison here's the output of regular traceoute:

```
traceroute  -n server.thegreenwebfoundation.org
```

Output:

```
traceroute to server.thegreenwebfoundation.org (85.17.184.227), 64 hops max, 52 byte packets
 1  192.168.178.1  6.021 ms  3.305 ms  9.805 ms
 2  83.169.183.46  20.051 ms  16.160 ms  12.516 ms
 3  88.134.234.89  12.418 ms  12.727 ms
    88.134.234.91  13.300 ms
 4  145.254.3.92  15.313 ms
    145.254.3.66  17.858 ms  15.459 ms
 5  145.254.2.209  25.308 ms
    145.254.2.207  31.324 ms
    145.254.2.209  36.510 ms
 6  145.254.2.209  28.430 ms
    145.254.2.207  33.089 ms  26.060 ms
 7  31.31.36.34  28.497 ms  22.877 ms  20.163 ms
 8  31.31.34.26  29.623 ms
```

**Comment by mrchrisadams** [comment]
Oh hang on, this dependency _is_ in the source code in this repo, already. Weird.

OK, if anyone's curious, here are the steps I've taken to reproduce this in a new virtual env:

https://gist.github.com/mrchrisadams/abedd78cd0c06d3ad464f0feb7a746d1

**Update:** I'm now wondering if the version on Pypi is missing the dependency - seeing as the last release on Pypi is a few years ago this might be the case.

**Comment by insomniacslk** [comment]
Hi @mrchrisadams , for some reason I didn't get any notification for this issue, apologies for the delay.

Re. `tabulate`, I should have clearly documented that you have to run `pip install -r rquirements.txt` from the source directory (this is [`requirements.txt`](https://github.com/insomniacslk/python-dublin-traceroute/blob/master/requirements.txt)). I will update the README.

Re. the output, we can try to debug it with tcpdump if this is still relevant to you

**Comment by insomniacslk** [comment]
Added reference to requirements.txt to readme. Let me know if this doesn't solve the issue for you
